const { EnkaClient } = require("enka-network-api");
const enka = new EnkaClient({ defaultLanguage: "en" });

const characters = enka.getAllCharacters();

for (const char of characters) {
    const name = char.name.get();
    const stars = char.stars;
    const element = char.element.name.get();

    console.log(`${name} (★${stars} ${element})`);
}
/* Example output
Kamisato Ayaka (★5 Cryo)
Jean (★5 Anemo)
Traveler (★5 Anemo)
Traveler (★5 Geo)
Traveler (★5 Electro)
Traveler (★5 Dendro)
Lisa (★4 Electro)
Traveler (★5 Anemo)
Traveler (★5 Geo)
Traveler (★5 Electro)
Traveler (★5 Dendro)
Barbara (★4 Hydro)
Kaeya (★4 Cryo)
Diluc (★5 Pyro)
Razor (★4 Electro)
Amber (★4 Pyro)
Venti (★5 Anemo)
Xiangling (★4 Pyro)
Beidou (★4 Electro)
Xingqiu (★4 Hydro)
Xiao (★5 Anemo)
Ningguang (★4 Geo)
Klee (★5 Pyro)
Zhongli (★5 Geo)
Fischl (★4 Electro)
Bennett (★4 Pyro)
Tartaglia (★5 Hydro)
Noelle (★4 Geo)
Qiqi (★5 Cryo)
Chongyun (★4 Cryo)
Ganyu (★5 Cryo)
Albedo (★5 Geo)
Diona (★4 Cryo)
Mona (★5 Hydro)
Keqing (★5 Electro)
Sucrose (★4 Anemo)
Xinyan (★4 Pyro)
Rosaria (★4 Cryo)
Hu Tao (★5 Pyro)
Kaedehara Kazuha (★5 Anemo)
Yanfei (★4 Pyro)
Yoimiya (★5 Pyro)
Thoma (★4 Pyro)
Eula (★5 Cryo)
Raiden Shogun (★5 Electro)
Sayu (★4 Anemo)
Sangonomiya Kokomi (★5 Hydro)
Gorou (★4 Geo)
Kujou Sara (★4 Electro)
Arataki Itto (★5 Geo)
Yae Miko (★5 Electro)
Shikanoin Heizou (★4 Anemo)
Yelan (★5 Hydro)
Aloy (★5 Cryo)
Shenhe (★5 Cryo)
Yun Jin (★4 Geo)
Kuki Shinobu (★4 Electro)
Kamisato Ayato (★5 Hydro)
Collei (★4 Dendro)
Dori (★4 Electro)
Tighnari (★5 Dendro)
Nilou (★5 Hydro)
Cyno (★5 Electro)
Candace (★4 Hydro)
Nahida (★5 Dendro)
Layla (★4 Cryo)
Wanderer (★5 Anemo)
Faruzan (★4 Anemo)
*/